### PR TITLE
Smashing magazine home-page heatmap

### PR DESCRIPTION
**Pull request by AlanSoto31**
The intention of this project was to practice visual hierarchy, cloning the main structure of the Smashing magazine home page and using a 4-unit grayscale, to order from the most attractive to the least attractive elements of each section. Mostly it was built with a 4 column grid layout and a bunch of div elements.

### CODE REVIEW

**Comment by AlanSoto31** [comment]
I have some problems with lighthouse linter, I committed package.json file by error, I mean I did not put it in the gitignore file. I tried to delete this file and pushing again but nothing happened, I tried to reset at a previous commit (package.json file error) and pushing again but nothing happened. Can you help me to fix this error, please?

**Comment by kubilaycaglayan** [comment]
> I have some problems with lighthouse linter, I committed package.json file by error, I mean I did not put it in the gitignore file. I tried to delete this file and pushing again but nothing happened, I tried to reset at a previous commit (package.json file error) and pushing again but nothing happened. Can you help me to fix this error, please?

We will work on it together :+1:

**Comment by AlanSoto31** [comment]
> > I have some problems with lighthouse linter, I committed package.json file by error, I mean I did not put it in the gitignore file. I tried to delete this file and pushing again but nothing happened, I tried to reset at a previous commit (package.json file error) and pushing again but nothing happened. Can you help me to fix this error, please?
> 
> We will work on it together

sure

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
Hello Team :wave: 
Status: Changes Required :recycle: 

Great job so far! Congratulations on creating a great heatmap! :star2: 
Let's cover some details to make your project great... :arrow_down: 

### Linter Checks

:bulb:  Can you please check this note from Oscar Mier, https://github.com/mateomh/Responsive-Design/pull/2#issuecomment-663788017
If it does not help, please try to turn off/on the GA on your repository settings.
Hope this helps :four_leaf_clover: 
I can see that you are successful at deleting the json file, so turning off and on hopefully will work :blush: 

- [ ]  [REQUIRED] Fix your GA errors.

### Readme
:bulb: [OPTIONAL] You can use backticks to create a `inline code`. It would be better if you can use this in your readme file. When you are talking about how to clone or how to cd into a folder. `cd path/to/file`

### General Layout

- [ ] [REQUIRED] It contains 3 articles, each takes one third of the width (content is not important) ([link to page](https://www.smashingmagazine.com/))
:bulb: I can't see this section on the heatmap. "Latest Posts"

**Screenshot from original page :camera_flash: **
three

- [ ]  [OPTIONAL]  I suggest you to use "main" and  "footer" HTML tags to have a semantic structure.

### That's it! After doing the changes, you can request another code review :blush: 

Thanks for your time and efforts :star: 
With all my respect... :pray:

**Comment by AlanSoto31** [comment]
I turned off/on GA but nothing

**Review by MuriloRoque — APPROVED** [review]
# Status: Approved :green_circle: 

### Hello @AlanSoto31 :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
